project1/project1/app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path('', views.hello_world, name='hello_world'),#http://127.0.0.1:8000
    path('info/', views.show_info, name='show_info'),#http://127.0.0.1:8000/info
    path('details/', views.show_details, name='show_details'), #http://127.0.0.1:8000/details
    path('hello/<str:name>/', views.say_hello, name='say_hello'),#http://127.0.0.1:8000/hello/Ігор
    path('car/<int:car_id>/', views.show_car_by_id, name='show_car_by_id'),#http://127.0.0.1:8000/car/1
    path('car/search/', views.search_cars, name='search_cars'),#http://127.0.0.1:8000/car/search?min_price=6900
    path('greet/', views.greeting, name='greeting'),
    path('car/add', views.add_car, name='add_car'),
    path('car/delete', views.delete_car, name='delete_car'),
    path('car/update', views.update_car, name='update_car'),
]

project1/project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("project1.app.urls"))
]

project1/project1/app/templates/app/add_car.html
{% extends 'app/base.html' %}

{% block title %} Додати автомобіль {% endblock %}

{% block content %}
    <h1>Додати автомобіль</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <button type="submit" class="btn btn-primary">Додати</button>
    </form>

    <a href="{% url 'app:show_info' %}" class="btn btn-secondary">Назад до списку</a>
{% endblock %}

project1/project1/app/templates/app/base.html
<html>
<head>
    <title>{% block title %} Автомобільний каталог {% endblock %}</title>
    <style>
        body {
            background: beige;
            margin: 0;
            padding: 0;
        }

        header {
            color: white;
            background: aqua;
        }

        footer {
            color: white;
            background: burlywood;
            text-align: center;
            padding: 20px;
        }

        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
        }

        .li_float {
            float: left;
        }

        .list {
            background-color: beige;
        }

        li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li a:hover {
            background-color: #111;
        }
    </style>
</head>
<body>
<header>
    <nav>
        <ul>
            <li class="li_float"><a href="/">Головна</a></li>
            <li class="li_float"><a href="/info">Каталог</a></li>
            <li class="li_float"><a href="/details">Детальніше</a></li>
            <li class="li_float"><a href="/car/add">Добавити авто</a></li>
            <li class="li_float"><a href="/car/delete">Видалити авто</a></li>
            <li class="li_float"><a href="/car/update">Оновити авто</a></li>
            <li class="li_float"><a href="/car/search">Пошук</a></li>
        </ul>
    </nav>
</header>

{% block content %} {% endblock %}

<footer>ITSTEP. All rights reserved. </footer>
</body>
</html>

project1/project1/app/templates/app/car_details.html
{% extends 'app/base.html' %}

{% block title %} Детальніше про машини {% endblock %}

{% block content %}
    <h1>Інформація про машини</h1>
    {% if cars %}
    <table style="width: 400px; margin-bottom: 30px" border="3">
        <tr style="height: 40px">
            <th>Параметр</th>
            <th>Значення</th>
        </tr>
        {% for car_id, car in cars.items %}
        <tr style="height: 40px">
            <td>ID</td>
            <td>{{ car_id }}</td>
        </tr>
        {% for key, value in car.items %}
        <tr style="height: 40px">
            <td>{{ key }}</td>
            <td>{{ value }}</td>
        </tr>
        {% endfor %}
        {% endfor %}
    </table>
    {% else %}
        <p>Автомобіль не знайдено.</p>
    {% endif %}
{% endblock %}

<!--<html>-->
<!--<head>-->
<!--   <title>Інформація про машини</title>-->
<!--</head>-->
<!--<body>-->
<!--    <h1>Інформація про машини</h1>-->
<!--    {% if cars %}-->
<!--    <table style="width: 400px; margin-bottom: 30px" border="3">-->
<!--        <tr style="height: 40px">-->
<!--            <th>Параметр</th>-->
<!--            <th>Значення</th>-->
<!--        </tr>-->
<!--        {% for car_id, car in cars.items %}-->
<!--        <tr style="height: 40px">-->
<!--            <td>ID</td>-->
<!--            <td>{{ car_id }}</td>-->
<!--        </tr>-->
<!--        {% for key, value in car.items %}-->
<!--        <tr style="height: 40px">-->
<!--            <td>{{ key }}</td>-->
<!--            <td>{{ value }}</td>-->
<!--        </tr>-->
<!--        {% endfor %}-->
<!--        {% endfor %}-->
<!--    </table>-->
<!--    {% else %}-->
<!--        <p>Автомобіль не знайдено.</p>-->
<!--    {% endif %}-->
<!--    <a href="{% url 'app:show_info' %}">Назад до списку</a>-->
<!--</body>-->
<!--</html>-->

project1/project1/app/templates/app/car_list.html
{% extends 'app/base.html' %}

{% block title %} Список машин {% endblock %}

{% block content %}
    <h1>Інформація про машини</h1>
    {% if cars %}
        <ol class="list">
            {% for car_id, car in cars.items %}
                <li>
<!--                    <strong>ID: {{ car_id }}</strong>-->
                    <a href="{% url 'app:show_car_by_id' car_id=car_id %}"><strong>ID: {{ car_id }}</strong></a>
                    <ul class="list">
                        {% for key, value in car.items %}
                            <li>
                                {{ key }} : {{ value }}
                            </li>
                        {% endfor %}
                    </ul>
                    <a href="{% url 'app:update_car' %}" class="btn btn-secondary">Оновити автомобіль</a>
                </li>
            <hr>
            {% endfor %}
        </ol>
    {% endif %}
    <a href="{% url 'app:add_car' %}" class="btn btn-secondary">Додати автомобіль</a>
    <a href="{% url 'app:delete_car' %}" class="btn btn-secondary">Видалити автомобіль</a>
{% endblock %}

<!--<html>-->
<!--<head>-->
<!--    <tilte>Список машин</tilte>-->
<!--</head>-->
<!--<body>-->
<!--    <h1>Інформація про машини</h1>-->
<!--    {% if cars %}-->
<!--        <ol>-->
<!--            {% for car_id, car in cars.items %}-->
<!--                <li>-->
<!--                    <strong>ID: {{ car_id }}</strong>-->
<!--                    <ul>-->
<!--                        {% for key, value in car.items %}-->
<!--                            <li>{{ key }} : {{ value }}</li>-->
<!--                        {% endfor %}-->
<!--                    </ul>-->
<!--                </li>-->
<!--            <hr>-->
<!--            {% endfor %}-->
<!--        </ol>-->
<!--    {% endif %}-->

<!--    <a href="{% url 'app:show_details' %}">Перейти до таблиці</a>-->
<!--</body>-->
<!--</html>-->

project1/project1/app/templates/app/delete_car.html
{% extends 'app/base.html' %}

{% block title %} Видалити автомобіль {% endblock %}

{% block content %}
    <h1>Видалити автомобіль</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <button type="submit" class="btn btn-primary">Видалити</button>
    </form>

    <a href="{% url 'app:show_info' %}" class="btn btn-secondary">Назад до списку</a>
{% endblock %}

project1/project1/app/templates/app/index.html
{% extends 'app/base.html' %}

{% block title %} Головна сторінка {% endblock %}

{% block content %}
    <h1>ITStep авто</h1>
    <p>Знайди автомобіль який підходить саме тобі!</p>
{% endblock %}

<!--<html>-->
<!--<head>-->
<!--    <title>Привіт з шаблону</title>-->
<!--</head>-->

<!--<body>-->
<!--    <h1>Заголовок шаблону</h1>-->
<!--    <p>Шаблони працюють</p>-->
<!--</body>-->
<!--</html>-->

project1/project1/app/templates/app/search_cars.html
{% extends 'app/base.html' %}

{% block title %} Результати пошуку {% endblock %}

{% block content %}
    <h1>Пошук авто</h1>
    <form method="GET">
        {{ form.as_p }}
        {{ form_year.as_p }}
        {{ form_model.as_p }}
        {{ form_mark.as_p }}
        <button type="submit" class="btn-primary">Пошук</button>
    </form>

    <h2>Результати пошуку</h2>
<!--    <p>-->
<!--        Знайдені автомобілі з ціною від <strong>{{ min_price|default:0 }}</strong> до <strong>{{ max_price|default:"Без обмежень" }}</strong>-->
<!--    </p>-->
<!--    <p>-->
<!--        Знайдені автомобілі з роком випуску <strong>{{ min_year|default:0 }}</strong> до <strong>{{ max_year|default:"Без обмежень" }}</strong>-->
<!--    </p>-->
    {% if filtered_cars %}
        <h3>Знайдено {{ filtered_cars|length }}</h3>
        <ol class="list">
            {% for car in filtered_cars %}
                <li>
                    <ul class="list">
                        {% for key, value in car.items %}
                            <li>{{ key|upper }} : {{ value }}</li>
                        {% endfor %}
                    </ul>
                </li>
            <hr>
            {% endfor %}
        </ol>
    {% else %}
        <p>За вашими крітеріями не знайдено жодного авто</p>
    {% endif %}
{% endblock %}


<!--<html>-->
<!--<head>-->
<!--    <title>Результати пошуку</title>-->
<!--</head>-->
<!--<body>-->
<!--    <h2>Результати пошуку</h2>-->
<!--    <p>-->
<!--        Знайдені автомобілі з ціною від <strong>{{ min_price|default:0 }}</strong> до <strong>{{ max_price|default:"Без обмежень" }}</strong>-->
<!--    </p>-->
<!--    {% if filtered_cars %}-->
<!--        <h3>Знайдено {{ filtered_cars|length }}</h3>-->
<!--        <ol>-->
<!--            {% for car in filtered_cars %}-->
<!--                <li>-->
<!--                    <ul>-->
<!--                        {% for key, value in car.items %}-->
<!--                            <li>{{ key|upper }} : {{ value }}</li>-->
<!--                        {% endfor %}-->
<!--                    </ul>-->
<!--                </li>-->
<!--            <hr>-->
<!--            {% endfor %}-->
<!--        </ol>-->
<!--    {% else %}-->
<!--        <p>За вашими крітеріями не знайдено жодного авто</p>-->
<!--    {% endif %}-->
<!--</body>-->
<!--</html>-->

project1/project1/app/templates/app/show_car_by_id.html
{% extends 'app/base.html' %}

{% block title %} Інформація про машину {% endblock %}

{% block content %}
    <h1>Інформація про машини</h1>
     <p>ID машини: {{ car_id }}</p>
    {% if car %}
        <p>Марка машини: {{ car.Марка }}</p>
        <p>Модель машини: {{ car.Модель }}</p>
        <p>Рік машини: {{ car.Рік }}</p>
        <p>Ціна машини: {{ car.Ціна }}</p>
    {% endif %}
{% endblock %}


<!--<html>-->
<!--<head>-->
<!--   <title>Інформація про машини</title>-->
<!--</head>-->
<!--<body>-->
<!--    <h1>Інформація про машини</h1>-->
<!--     <p>ID машини: {{ car_id }}</p>-->
<!--    {% if car %}-->
<!--        <p>Марка машини: {{ car.Марка }}</p>-->
<!--        <p>Модель машини: {{ car.Модель }}</p>-->
<!--        <p>Рік машини: {{ car.Рік }}</p>-->
<!--        <p>Ціна машини: {{ car.Ціна }}</p>-->
<!--    {% endif %}-->
<!--    <a href="{% url 'app:show_info' %}">Назад до списку</a>-->
<!--    <a href="{% url 'app:show_details' %}">Перейти до таблиці</a>-->
<!--</body>-->
<!--</html>-->

project1/project1/app/templates/app/tags.html
{#1.Умовні теги#}
{#{% if %}#}
{#код#}
{#{% endif %}#}

{#else#}

{#{% ifequal a b %} }}#}
{#код#}
{#{% endifequal %}#}

{#2. Цикли#}
{#{% for key, value  in dictionary %}#}
{#    Key: {{ key }}#}
{#    Value: {{ value }}#}
{#{% endfor %}#}

{#3. Включення#}
{#{% include 'назва.html' %}#}

{#4. URL#}
{#{% url 'path/to/resourse' параметри %}#}
{#<a href=">Link</a>#}

project1/project1/app/templates/app/update_car.html
{% extends 'app/base.html' %}

{% block title %} Оновити данні автомобіля {% endblock %}

{% block content %}
    <h1>Оновити данні автомобіля</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <button type="submit" class="btn btn-primary">Оновити</button>
    </form>

    <a href="{% url 'app:show_info' %}" class="btn btn-secondary">Назад до списку</a>
{% endblock %}